Demonstrate different handling of `Action<T>` by the Kotlin compiler
`Action<T>` combined with `SamWithReceiverAnnotations` should cause
the Kotlin compiler to always treat `Action<T>` as an alias to
`T.() -> Unit`, in other words:

```kotlin
typealias Action<T> = T.() -> Unit
```

Unfortunately that's currently not always the case and it depends on
whether the callee is defined in Kotlin or not.

When the callee is defined in Kotlin, trying to pass a lambda
expression where a, say, `Action<CopySpec>` is expected will result in
the following error:

```
Error: Type mismatch: inferred type is () -> ??? but Action<CopySpec> was expected
```

See gradle/kotlin-dsl#522